#!/usr/bin/env python
import sys

def all_checks():
    try:
        from what_the_duck.sanity_checks import do_all_checks
        from duckietown_utils import logger, col_logging  # @UnusedImport
    except ImportError as e:
        sys.stderr.write('Could not import duckietown_utils and what_the_duck packages:\n%s\n' % e)
        sys.exit(255)
    
    nfailures = do_all_checks()

    if nfailures == 0:
        logger.info('Everything went well.')
        sys.exit(0)
    else:
        logger.error('what_the_duck obtained %d failures.' % nfailures)
        sys.exit(nfailures)


if __name__ == '__main__':
    all_checks()
